### ISSUE TITLE
No such command 'great'

### ISSUE THREAD

**Issue by noklam** [tamsanh/kedro-great#9]
Kedro: 0.16.4
OS: Window 10

```
pip install kedro-great
kedro great init
```

> Error: Loading global commands from kedro-great = kedro_great:commands
> 
> Usage: kedro [OPTIONS] COMMAND [ARGS]...
> Try 'kedro -h' for help.
> 
> Error: No such command 'great'.

**Comment by bensdm** [comment]
same issue here

**Comment by rdoume** [comment]
Got the same issue, solved it by rolling back to kedro 16.2.

**Comment by noklam** [comment]
> Got the same issue, solved it by rolling back to kedro 16.2.

@rdoume 
This doesn't solve my problem, I hit the same error.

**Comment by tamsanh** [comment]
This may be an issue with some of the version requirements. Can you paste the full error message?

```
Traceback (most recent call last):
  File "/Users/tamu/.pyenv/versions/3.7.6/lib/python3.7/site-packages/kedro/framework/cli/cli.py", line 683, in load_entry_points
    entry_point_commands.append(entry_point.load())
  File "/Users/tamu/.pyenv/versions/3.7.6/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2442, in load
    self.require(*args, **kwargs)
  File "/Users/tamu/.pyenv/versions/3.7.6/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2465, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/Users/tamu/.pyenv/versions/3.7.6/lib/python3.7/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (botocore 1.17.47 (/Users/tamu/.pyenv/versions/3.7.6/lib/python3.7/site-packages), Requirement.parse('botocore<1.16.0,>=1.15.5'), {'boto3'})
Error: Loading global commands from kedro-great = kedro_great:commands
/Users/tamu/.pyenv/versions/3.7.6/lib/python3.7/site-packages/setuptools/depends.py:2: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
Usage: kedro [OPTIONS] COMMAND [ARGS]...
Try 'kedro -h' for help.

Error: No such command 'great'.```

**Comment by noklam** [comment]
I cannot reproduce my error before exactly. I remember manually downgraded requests & cachetools & pyspark before.
If I upgraded my requests library I will get this. 
```
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (requests 2.24.0 (c:\users\channo.oocldm\appdata\local\continuum\anaconda3\lib\site-packages), Requirement.parse('requests<2.24,>=2.20'), {'great-expectations'})
```

**Comment by noklam** [comment]
Anyway, I solved the issue by looking at the `VersionConflict` and downgrade all those library manually.
